import prisma from "./prisma";

export const skill = [
    { name: "Web Development", category: "Technology" },
    { name: "Graphic Design", category: "Creative" },
    { name: "Content Writing", category: "Marketing" },
    { name: "Data Analysis", category: "Business" },
    { name: "Machine Learning", category: "Technology" },
    { name: "Social Media Marketing", category: "Marketing" },
    { name: "Project Management", category: "Business" },
    { name: "User Experience Design (UX)", category: "Design" },
    { name: "Copywriting", category: "Marketing" },
    { name: "Software Engineering", category: "Technology" },
    { name: "SEO Optimization", category: "Marketing" },
    { name: "Mobile Development", category: "Technology" },
    { name: "App Development", category: "Technology" },
    { name: "Game Development", category: "Technology" },
    { name: "Database Administration", category: "Technology" },
    { name: "Network Administration", category: "Technology" },
    { name: "Cloud Computing", category: "Technology" },
    { name: "Cybersecurity", category: "Technology" },
    { name: "Artificial Intelligence (AI)", category: "Technology" },
    { name: "Internet of Things (IoT)", category: "Technology" },
    { name: "Blockchain Development", category: "Technology" },
    { name: "Virtual Reality (VR)", category: "Technology" },
    { name: "Augmented Reality (AR)", category: "Technology" },
    { name: "Robotics", category: "Technology" },
    { name: "Product Management", category: "Business" },
    { name: "Business Development", category: "Business" },
    { name: "Sales", category: "Business" },
    { name: "Marketing Management", category: "Marketing" },
    { name: "Public Relations (PR)", category: "Marketing" },
    { name: "Email Marketing", category: "Marketing" },
    { name: "Content Marketing", category: "Marketing" },
    { name: "Social Media Management", category: "Marketing" },
    { name: "Pay-Per-Click (PPC) Advertising", category: "Marketing" },
    { name: "Search Engine Marketing (SEM)", category: "Marketing" },
    { name: "Affiliate Marketing", category: "Marketing" },
    { name: "Graphic Design (Print)", category: "Creative" },
    { name: "Web Design", category: "Creative" },
    { name: "User Interface (UI) Design", category: "Design" },
    { name: "Motion Graphics", category: "Creative" },
    { name: "Video Editing", category: "Creative" },
    { name: "Photography", category: "Creative" },
    { name: "Animation", category: "Creative" },
    { name: "3D Modeling", category: "Creative" },
    { name: "Copy Editing", category: "Marketing" },
    { name: "Proofreading", category: "Marketing" },
    { name: "Voice User Interface (VUI) Design", category: "Design" },
    { name: "Human-Computer Interaction (HCI)", category: "Technology" },
    { name: "Quantum Computing", category: "Technology" },
    { name: "Natural Language Processing (NLP)", category: "Technology" },
    { name: "Data Science", category: "Technology" },
    { name: "Big Data Analytics", category: "Technology" },
    { name: "Bioinformatics", category: "Science" },
    { name: "Genetic Engineering", category: "Science" },
    { name: "Neural Networks", category: "Technology" },
    { name: "Deep Learning", category: "Technology" },
    { name: "Computer Vision", category: "Technology" },
    { name: "AR/VR Development", category: "Technology" },
    { name: "Cloud Architecture", category: "Technology" },
    { name: "IT Consulting", category: "Technology" },
    { name: "E-commerce Management", category: "Business" },
    { name: "Supply Chain Management", category: "Business" },
    { name: "Financial Analysis", category: "Business" },
    { name: "Investment Banking", category: "Finance" },
    { name: "Cryptocurrency Trading", category: "Finance" },
    { name: "Risk Management", category: "Finance" },
    { name: "Compliance Management", category: "Legal" },
    { name: "Corporate Law", category: "Legal" },
    { name: "Intellectual Property Law", category: "Legal" },
    { name: "Environmental Law", category: "Legal" },
    { name: "Criminal Law", category: "Legal" },
    { name: "Family Law", category: "Legal" },
    { name: "Immigration Law", category: "Legal" },
    { name: "Public Health Policy", category: "Public Health" },
    { name: "Epidemiology", category: "Public Health" },
    { name: "Health Informatics", category: "Public Health" },
    { name: "Healthcare Administration", category: "Healthcare" },
    { name: "Medical Billing and Coding", category: "Healthcare" },
    { name: "Nursing", category: "Healthcare" },
    { name: "Clinical Research", category: "Healthcare" },
    { name: "Medical Writing", category: "Healthcare" },
    { name: "Telemedicine", category: "Healthcare" },
    { name: "Medical Illustration", category: "Healthcare" },
    { name: "Clinical Psychology", category: "Psychology" },
    { name: "Educational Psychology", category: "Psychology" },
    { name: "Sports Psychology", category: "Psychology" },
    { name: "Forensic Psychology", category: "Psychology" },
    { name: "Counseling Psychology", category: "Psychology" },
    { name: "Industrial-Organizational Psychology", category: "Psychology" },
    { name: "Developmental Psychology", category: "Psychology" },
    { name: "Experimental Psychology", category: "Psychology" },
    { name: "Social Psychology", category: "Psychology" },
    { name: "Behavioral Economics", category: "Economics" },
    { name: "Microeconomics", category: "Economics" },
    { name: "Macroeconomics", category: "Economics" },
    { name: "Financial Economics", category: "Economics" },
    { name: "International Economics", category: "Economics" },
    { name: "Labor Economics", category: "Economics" },
    { name: "Health Economics", category: "Economics" },
    { name: "Urban Economics", category: "Economics" },
    { name: "Environmental Economics", category: "Economics" },
    { name: "Quantitative Finance", category: "Finance" },
    { name: "Behavioral Finance", category: "Finance" },
    { name: "Corporate Finance", category: "Finance" },
    { name: "Venture Capital", category: "Finance" },
    { name: "Private Equity", category: "Finance" },
    { name: "Hedge Fund Management", category: "Finance" },
    { name: "Financial Planning", category: "Finance" },
    { name: "Retirement Planning", category: "Finance" },
    { name: "Tax Planning", category: "Finance" },
    { name: "Personal Finance", category: "Finance" },
    { name: "Financial Modeling", category: "Finance" },
    { name: "Derivatives Trading", category: "Finance" },
    { name: "Actuarial Science", category: "Finance" },
    { name: "Corporate Strategy", category: "Business" },
    { name: "Competitive Intelligence", category: "Business" },
    { name: "Market Research", category: "Business" },
    { name: "Brand Management", category: "Marketing" },
    { name: "Event Planning", category: "Marketing" },
    { name: "Customer Relationship Management (CRM)", category: "Marketing" },
    { name: "Influencer Marketing", category: "Marketing" },
    { name: "Brand Ambassadorship", category: "Marketing" },
    { name: "Community Management", category: "Marketing" },
    { name: "Digital Strategy", category: "Marketing" },
    { name: "Mobile Marketing", category: "Marketing" },
    { name: "Growth Hacking", category: "Marketing" },
    { name: "Inbound Marketing", category: "Marketing" },
    { name: "Outbound Marketing", category: "Marketing" },
    { name: "Event Marketing", category: "Marketing" },
    { name: "Experiential Marketing", category: "Marketing" },
    { name: "Branded Content", category: "Marketing" },
    { name: "Guerrilla Marketing", category: "Marketing" },
    { name: "Direct Marketing", category: "Marketing" },
    { name: "Cause Marketing", category: "Marketing" },
    { name: "Neuromarketing", category: "Marketing" },
    { name: "Sustainable Marketing", category: "Marketing" },
    { name: "Ethical Hacking", category: "Technology" },
    { name: "Digital Forensics", category: "Technology" },
    { name: "Penetration Testing", category: "Technology" },
    { name: "Cryptography", category: "Technology" },
    { name: "Incident Response", category: "Technology" },
    { name: "Cyber Threat Intelligence", category: "Technology" },
    { name: "Security Architecture", category: "Technology" },
    { name: "Vulnerability Management", category: "Technology" },   
    { name: "Security Operations", category: "Technology"},
    { name: "Study Skills", category: "Academic" },
    { name: "Time Management", category: "Personal Development" },
    { name: "Note-taking", category: "Academic" },
    { name: "Research Skills", category: "Academic" },
    { name: "Critical Thinking", category: "Academic" },
    { name: "Problem-solving", category: "Academic" },
    { name: "Public Speaking", category: "Communication" },
    { name: "Writing Skills", category: "Academic" },
    { name: "Mathematics", category: "Academic" },
    { name: "Physics", category: "Academic" },
    { name: "Chemistry", category: "Academic" },
    { name: "Biology", category: "Academic" },
    { name: "History", category: "Academic" },
    { name: "Literature", category: "Academic" },
    { name: "Foreign Language Proficiency", category: "Language" },
    { name: "Computer Literacy", category: "Technology" },
    { name: "Programming Skills", category: "Technology" },
    { name: "Data Analysis", category: "Technology" },
    { name: "Graphic Design", category: "Creative" },
    { name: "Photography", category: "Creative" },
    { name: "Music Skills", category: "Creative" },
    { name: "Artistic Abilities", category: "Creative" },
    { name: "Sports Skills", category: "Physical" },
    { name: "Teamwork", category: "Personal Development" },
    { name: "Leadership", category: "Personal Development" },
    { name: "Adaptability", category: "Personal Development" },
    { name: "Networking", category: "Personal Development" },
    { name: "Financial Literacy", category: "Personal Development" },
    { name: "Entrepreneurial Skills", category: "Business" },
    { name: "Marketing Knowledge", category: "Business" },
    { name: "Sales Skills", category: "Business" },
    { name: "Customer Service", category: "Business" },
    { name: "Project Management", category: "Business" },
    { name: "Event Planning", category: "Personal Development" },
    { name: "Volunteering", category: "Personal Development" },
    { name: "Community Engagement", category: "Personal Development" },
    { name: "Emotional Intelligence", category: "Personal Development" },
    { name: "Self-discipline", category: "Personal Development" },
    { name: "Creative Problem-solving", category: "Personal Development" },
    { name: "Digital Marketing Skills", category: "Business" },
    { name: "Presentation Skills", category: "Communication" },
    { name: "Debating Skills", category: "Communication" },
    { name: "Conflict Resolution", category: "Personal Development" },
    { name: "Cultural Awareness", category: "Personal Development" },
    { name: "Resume Writing", category: "Career Development" },
    { name: "Interview Preparation", category: "Career Development" },
    { name: "Job Search Strategies", category: "Career Development" },
    { name: "Internship Experience", category: "Career Development" },
    { name: "Study Abroad Experience", category: "Academic" },
    { name: "Time Management Apps", category: "Technology" },
    { name: "Online Learning Platforms", category: "Technology" },
    { name: "Critical Reading Skills", category: "Academic" },
    { name: "Presentation Software", category: "Technology" },
    { name: "Online Collaboration Tools", category: "Technology" },
    { name: "Financial Planning", category: "Personal Development" },
    { name: "Budgeting", category: "Personal Development" },
    { name: "Investment Knowledge", category: "Personal Development" },
    { name: "Mindfulness Practices", category: "Personal Development" },
    { name: "Health and Wellness", category: "Personal Development" },
    { name: "Public Speaking Anxiety Management", category: "Personal Development" },
    { name: "Social Media Management", category: "Technology" },
    { name: "Digital Photography", category: "Creative" },
    { name: "Video Editing Skills", category: "Creative" },
    { name: "Web Design Skills", category: "Technology" },
    { name: "Coding Bootcamp Experience", category: "Technology" },
    { name: "Online Course Certificates", category: "Academic" },
    { name: "Effective Communication Skills", category: "Communication" },
    { name: "Learning Agility", category: "Personal Development" },
    { name: "Research Paper Writing", category: "Academic" },
    { name: "Technical Writing Skills", category: "Academic" },
    { name: "Collaborative Problem-solving", category: "Personal Development" },
    { name: "Analytical Skills", category: "Academic" },
    { name: "Language Proficiency Certificates", category: "Language" },
    { name: "Computer Science Competitions", category: "Technology" },
    { name: "Graphic Design Competitions", category: "Creative" },
    { name: "Music Competitions", category: "Creative" },
    { name: "Leadership Experience", category: "Personal Development" },
    { name: "Financial Management Skills", category: "Personal Development" },
    { name: "Entrepreneurial Experience", category: "Business" },
    { name: "Marketing Campaigns", category: "Business" },
    { name: "Sales Experience", category: "Business" },
    { name: "Customer Service Experience", category: "Business" },
    { name: "Project Management Experience", category: "Business" },
    { name: "Event Planning Experience", category: "Personal Development" },
    { name: "Volunteering Experience", category: "Personal Development" },
    { name: "Community Engagement Experience", category: "Personal Development" },
    { name: "Emotional Intelligence Training", category: "Personal Development" },
    { name: "Coding Experience", category: "Technology" },
    { name: "Design Thinking Skills", category: "Creative" },
    { name: "Problem-solving Skills", category: "Academic" },
    { name: "Leadership Training", category: "Personal Development" },
    { name: "Financial Literacy Workshops", category: "Personal Development" },
    { name: "Digital Marketing Internship", category: "Business" },
    { name: "Presentation Skills Workshops", category: "Communication" },
    { name: "Career Counseling Sessions", category: "Career Development" },
    { name: "Study Skills Workshops", category: "Academic" },
    { name: "Language Immersion Programs", category: "Language" },
    { name: "Digital Media", category: "Technology" },
    { name: "Marketing", category: "Business" },
    { name: "Sales", category: "Business" },
    { name: "Event Management", category: "Personal Development" },
    { name: "Community Outreach", category: "Personal Development" },
    { name: "Education", category: "Academic" },
    { name: "Non-profit Organizations", category: "Community Development" },
    { name: "Environmental Conservation", category: "Environmental" },
    { name: "Healthcare", category: "Healthcare" },
    { name: "Finance", category: "Finance" },
    { name: "Human Resources", category: "Business" },
    { name: "Journalism", category: "Communication" },
    { name: "Graphic Design", category: "Creative" },
    { name: "Web Development", category: "Technology" },
    { name: "Data Analysis", category: "Technology" },
    { name: "Software Engineering", category: "Technology" },
    { name: "Public Relations", category: "Communication" },
    { name: "Content Writing", category: "Communication" },
    { name: "Social Media Management", category: "Technology" },
    { name: "Market Research", category: "Business" },
    { name: "Project Management", category: "Business" },
    { name: "Business Development", category: "Business" },
    { name: "Humanitarian Aid", category: "Community Development" },
    { name: "Public Policy", category: "Government" },
    { name: "Law", category: "Legal" },
    { name: "Urban Planning", category: "Community Development" },
    { name: "Social Work", category: "Community Development" },
    { name: "Environmental Policy", category: "Environmental" },
    { name: "Health Policy", category: "Healthcare" },
    { name: "Finance Management", category: "Finance" },
    { name: "Education Policy", category: "Education" },
    { name: "Technology Consulting", category: "Technology" },
    { name: "Digital Marketing", category: "Business" },
    { name: "Software Development", category: "Technology" },
    { name: "UX/UI Design", category: "Creative" },
    { name: "Market Analysis", category: "Business" },
    { name: "Data Visualization", category: "Technology" },
    { name: "Investment Banking", category: "Finance" },
    { name: "Supply Chain Management", category: "Business" },
    { name: "Logistics", category: "Business" },
    { name: "Healthcare Administration", category: "Healthcare" },
    { name: "Social Media Marketing", category: "Technology" },
    { name: "Brand Management", category: "Business" },
    { name: "Event Planning", category: "Personal Development" },
    { name: "Leadership Development", category: "Personal Development" },
    { name: "Community Engagement", category: "Personal Development" },
    { name: "Personal Branding", category: "Personal Development" },
    { name: "Fundraising", category: "Personal Development" },
    { name: "Grant Writing", category: "Personal Development" },
    { name: "Non-profit Management", category: "Business" },
    { name: "Conflict Resolution", category: "Personal Development" },
    { name: "Cultural Sensitivity", category: "Personal Development" },
    { name: "Diversity and Inclusion", category: "Personal Development" },
    { name: "Digital Literacy", category: "Technology" },
    { name: "Cybersecurity", category: "Technology" },
    { name: "Network Security", category: "Technology" },
    { name: "Cloud Computing", category: "Technology" },
    { name: "Artificial Intelligence", category: "Technology" },
    { name: "Machine Learning", category: "Technology" },
    { name: "Data Science", category: "Technology" },
    { name: "Robotics", category: "Technology" },
    { name: "Augmented Reality", category: "Technology" },
    { name: "Virtual Reality", category: "Technology" },
    { name: "Blockchain", category: "Technology" },
    { name: "Internet of Things (IoT)", category: "Technology" },
    { name: "Data Analytics", category: "Technology" },
    { name: "UX Research", category: "Technology" },
    { name: "User Interface Design", category: "Creative" },
    { name: "User Experience Design", category: "Creative" },
    { name: "Content Creation", category: "Communication" },
    { name: "Video Production", category: "Creative" },
    { name: "Animation", category: "Creative" },
    { name: "Illustration", category: "Creative" },
    { name: "Game Design", category: "Technology" },
    { name: "App Development", category: "Technology" },
    { name: "Mobile Development", category: "Technology" },
    { name: "Web Development", category: "Technology" },
    { name: "SEO", category: "Technology" },
    { name: "Content Marketing", category: "Business" },
    { name: "Email Marketing", category: "Business" },
    { name: "Social Media Management", category: "Technology" },
    { name: "Digital Advertising", category: "Business" },
    { name: "Copywriting", category: "Communication" },
    { name: "Graphic Design", category: "Creative" },
    { name: "Public Relations", category: "Communication" },
    { name: "Market Research", category: "Business" },
    { name: "Sales", category: "Business" },
    { name: "Customer Service", category: "Business" },
    { name: "Project Management", category: "Business" },
    { name: "Business Analysis", category: "Business" },
    { name: "Business Strategy", category: "Business" },
    { name: "Financial Analysis", category: "Finance" },
    { name: "Investment Banking", category: "Finance" },
    { name: "Management Consulting", category: "Business" },
    { name: "Accounting", category: "Finance" },
    { name: "Auditing", category: "Finance" },
    { name: "Taxation", category: "Finance" },
    { name: "Risk Management", category: "Finance" },
    { name: "Actuarial Science", category: "Finance" },
    { name: "Human Resources", category: "Business" },
    { name: "Talent Acquisition", category: "Business" },
    { name: "Employee Relations", category: "Business" },
    { name: "Training and Development", category: "Business" },
    { name: "Compensation and Benefits", category: "Business" },
    { name: "Organizational Development", category: "Business" },
    { name: "Performance Management", category: "Business" },
    { name: "Diversity and Inclusion", category: "Business" },
    { name: "HR Analytics", category: "Business" },
    { name: "Legal Research", category: "Legal" },
    { name: "Contract Law", category: "Legal" },
    { name: "Criminal Law", category: "Legal" },
    { name: "Civil Law", category: "Legal" },
    { name: "Family Law", category: "Legal" },
    { name: "Intellectual Property Law", category: "Legal" },
    { name: "Environmental Law", category: "Legal" },
    { name: "Health Law", category: "Legal" },
    { name: "Immigration Law", category: "Legal" },
    { name: "Corporate Law", category: "Legal" },
    { name: "International Law", category: "Legal" },
    { name: "Human Rights Law", category: "Legal" },
    { name: "Labor Law", category: "Legal" },
    { name: "Tax Law", category: "Legal" },
    { name: "Administrative Law", category: "Legal" },
    { name: "Real Estate Law", category: "Legal" },
    { name: "Litigation", category: "Legal" },
    { name: "Arbitration", category: "Legal" },
    { name: "Mediation", category: "Legal" },
    { name: "Legal Writing", category: "Legal" },
    { name: "Legal Advocacy", category: "Legal" },
    { name: "Legal Consulting", category: "Legal" },
    { name: "Legal Compliance", category: "Legal" },
    { name: "Legal Technology", category: "Legal" },
    { name: "Legal Education", category: "Legal" },
    { name: "Legal Aid", category: "Legal" },
    { name: "Policy Research", category: "Government" },
    { name: "Legislative Affairs", category: "Government" },
    { name: "Political Campaigning", category: "Government" },
    { name: "Diplomacy", category: "Government" },
    { name: "International Relations", category: "Government" },
    { name: "Public Policy Analysis", category: "Government" },
    { name: "Policy Advocacy", category: "Government" },
    { name: "Government Relations", category: "Government" },
    { name: "Public Administration", category: "Government" },
    { name: "Non-profit Management", category: "Business" },
    { name: "Fundraising", category: "Business" },
    { name: "Grant Writing", category: "Communication" },
    { name: "Volunteer Management", category: "Community Development" },
    { name: "Social Entrepreneurship", category: "Business" },
    { name: "Philanthropy", category: "Business" },
    { name: "Fund Management", category: "Finance" },
    { name: "Non-profit Finance", category: "Finance" },
    { name: "Impact Investing", category: "Finance" },
    { name: "Social Impact Assessment", category: "Business" },
    { name: "Corporate Social Responsibility", category: "Business" },
    { name: "Community Development", category: "Community Development" },
    { name: "International Development", category: "Community Development" },
    { name: "Urban Development", category: "Community Development" },
    { name: "Rural Development", category: "Community Development" },
    { name: "Economic Development", category: "Community Development" },
    { name: "Social Work", category: "Community Development" },
    { name: "Disaster Relief", category: "Community Development" },
    { name: "Public Health", category: "Healthcare" },
    { name: "Global Health", category: "Healthcare" },
    { name: "Healthcare Administration", category: "Healthcare" },
    { name: "Healthcare Policy", category: "Healthcare" },
    { name: "Health Education", category: "Healthcare" },
    { name: "Health Informatics", category: "Healthcare" },
    { name: "Health Promotion", category: "Healthcare" },
    { name: "Health Advocacy", category: "Healthcare" },
    { name: "Mental Health", category: "Healthcare" },
    { name: "Nutrition", category: "Healthcare" },
    { name: "Epidemiology", category: "Healthcare" },
    { name: "Biostatistics", category: "Healthcare" },
    { name: "Health Research", category: "Healthcare" },
    { name: "Healthcare Consulting", category: "Healthcare" },
    { name: "Health Technology", category: "Healthcare" },
    { name: "Medical Devices", category: "Healthcare" },
    { name: "Pharmaceuticals", category: "Healthcare" },
    { name: "Biotechnology", category: "Healthcare" },
    { name: "Clinical Research", category: "Healthcare" },
    { name: "Laboratory Science", category: "Healthcare" },
    { name: "Medical Imaging", category: "Healthcare" },
    { name: "Telemedicine", category: "Healthcare" },
    { name: "Healthcare Marketing", category: "Healthcare" },
    { name: "Healthcare Analytics", category: "Healthcare" },
    { name: "Healthcare Finance", category: "Healthcare" },
    { name: "Healthcare Operations", category: "Healthcare" },
    { name: "Healthcare Management", category: "Healthcare" },
    { name: "Healthcare Quality Improvement", category: "Healthcare" },
    { name: "Healthcare Informatics", category: "Healthcare" },
    { name: "Healthcare Policy Analysis", category: "Healthcare" },
    { name: "Healthcare Innovation", category: "Healthcare" }
];

export const course = [
    { name: "BACHELOR OF SCIENCE IN COMPUTER SCIENCE" },
    { name: "BACHELOR OF SCIENCE IN INFORMATION TECHNOLOGY" },
    { name: "BACHELOR OF SCIENCE IN CIVIL ENGINEERING" },
    { name: "BACHELOR OF SCIENCE IN COMPUTER ENGINEERING" },
    { name: "BACHELOR OF SCIENCE IN ELECTRICAL ENGINEERING" },
    { name: "BACHELOR OF SCIENCE IN ELECTRONIC ENGINEERING" },
    { name: "BACHELOR OF SCIENCE IN MECHANICAL ENGINEERING" },
    { name: "BACHELOR OF EARLY CHILDHOOD EDUCATION" },
    { name: "BACHELOR OF ELEMENTARY EDUCATION" },
    { name: "BACHELOR OF ELEMENTARY EDUCATION MAJOR IN EARLY CHILDHOOD EDUCATION" },
    { name: "BACHELOR OF ELEMENTARY EDUCATION MAJOR IN GENERAL EDUCATION" },
    { name: "BACHELOR OF ELEMENTARY EDUCATION MAJOR IN SPECIAL EDUCATION" },
    { name: "BACHELOR OF SECONDARY EDUCATION MAJOR IN ENGLISH" },
    { name: "BACHELOR OF SECONDARY EDUCATION MAJOR IN FILIPINO" },
    { name: "BACHELOR OF SECONDARY EDUCATION MAJOR IN MATHEMATICS" },
    { name: "BACHELOR OF SECONDARY EDUCATION MAJOR IN SCIENCE" },
    { name: "BACHELOR OF SPECIAL NEEDS EDUCATION:GENERALIST" },
    { name: "BACHELOR OF SCIENCE IN ACCOUNTANCY" },
    { name: "BACHELOR OF SCIENCE IN BUSINESS ADMINISTRATION MAJOR IN FINANCIAL MANAGEMENT" },
    { name: "BACHELOR OF SCIENCE IN BUSINESS ADMINISTRATION MAJOR IN MANAGEMENT ACCOUNTING" },
    { name: "BACHELOR OF SCIENCE IN BUSINESS ADMINISTRATION MAJOR IN MARKETING MANAGEMENT" },
    { name: "BACHELOR OF SCIENCE IN TOURISM MANAGEMENT" },
    { name: "BACHELOR OF ARTS IN MASS COMMUNICATION" },
    { name: "BACHELOR OF SCIENCE IN HOSPITALITY MANAGEMENT" },
    { name: "BACHELOR OF SCIENCE IN PSYCHOLOGY" },
    { name: "BACHELOR OF SCIENCE IN NURSING" },
    { name: "BACHELOR OF SCIENCE IN CRIMINOLOGY" },
    { name: "DOCTOR OF PHILOSOPHY EDUCATIONAL LEADERSHIP AND MANAGEMENT" },
    { name: "MASTER IN EDUCATION MAJOR IN EDUCATIONAL LEADERSHIP" },
    { name: "MASTER IN EDUCATION MAJOR IN ENGLISH LANGUAGE TEACHING" },
    { name: "MASTER IN INFORMATION TECHNOLOGY" },
    { name: "MASTER OF ARTS IN EDUCATION MAJOR IN EDUCATIONAL MANAGEMENT" }
]
